- platform: mqtt
  name: "Iluminação da Sacada"
  payload_on: "ON"
  payload_off: "OFF"
  state_topic: "stat/luz-sacada/POWER"
  command_topic: "cmnd/luz-sacada/POWER"
  availability_topic: "tele/luz-sacada/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
  icon: mdi:television-classic
  
