slid_hora_liga_tv:
  name: Ref Hora Liga TV
  icon: mdi:timer
  initial: 6
  min: 0
  max: 23
  step: 1 
  
slid_minuto_liga_tv:
  name: Ref Minuto Liga TV
  icon: mdi:timer
  initial: 15
  min: 0
  max: 59
  step: 1 
  
slid_hora_desliga_tv:
  name: Ref Hora Desliga TV
  icon: mdi:timer
  initial: 6
  min: 0
  max: 23
  step: 1 
  
slid_minuto_desliga_tv:
  name: Ref Minuto Desliga TV
  icon: mdi:timer
  initial: 45
  min: 0
  max: 59
  step: 1 
 
slid_ctl_ilm_cozinha:
  name: Limite Iluminacao Cozinha
  icon: mdi:timer
  initial: 2
  min: 2
  max: 10
  step: 1 
  
slid_ctl_ilm_sala:
  name: Limite Iluminacao Sala
  icon: mdi:timer
  initial: 2
  min: 2
  max: 10
  step: 1 
  
slid_ctl_ilm_corredor:
  name: Limite Iluminacao Corredor
  icon: mdi:timer
  initial: 2
  min: 2
  max: 10
  step: 1 
  
slid_ctl_ilm_filho:
  name: Limite Iluminacao Filho
  icon: mdi:timer
  initial: 3
  min: 2
  max: 10
  step: 1 
  
slid_ctl_ilm_casal:
  name: Limite Iluminacao Casal
  icon: mdi:timer
  initial: 5
  min: 2
  max: 10
  step: 1
  
slid_ctl_ilm_sacada:
  name: Limite Iluminacao Sacada
  icon: mdi:timer
  initial: 2
  min: 2
  max: 10
  step: 1
  
slid_lim_inf_ar:
  name: Limite Inferior AR
  icon: mdi:timer
  initial: 24
  min: 22
  max: 26
  step: 0.5
 
slid_lim_sup_ar:
  name: Limite Superior AR
  icon: mdi:timer
  initial: 26
  min: 24
  max: 28
  step: 0.5