- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: memory_free
    - type: memory_use
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    - type: ipv4_address
      arg: eth0